version: 0.2

phases:
  build:
    commands:
      - echo Building the production-ready app...
      - npm install
      - npm run build

post_build:
  commands:
    - echo Syncing build artifacts to S3...
    - aws s3 sync build/ s3://prod-society-fe/

artifacts:
  files: []  # No need to specify files since the sync is done in post_build
