version: 0.2

phases:
  build:
    commands:
      - echo Building the production-ready app...
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'

post_build:
  commands:
    - echo Syncing build artifacts to S3...
    - aws s3 sync build/ s3://your-s3-bucket-name/
